Update 500_ci.md
PluribusDigital/dev-guide pull request #2
Opened 2018-10-19 17:00 UTC by JeffreyMFarley

2018-10-19 17:27 UTC, bengm commented on _sections/500_ci.md
> +* _Use a CI server:_ There are several free CI servers available.  We use [Travis](https://travis-ci.org/STSILABS) or [CircleCI](https://circleci.com/gh/STSILABS).  These should be configured to buil
```suggestion
* _Use a CI server:_ There are several free CI servers available.  We use [Travis](https://travis-ci.org/STSILABS) or [CircleCI](https://circleci.com/gh/STSILABS) for open source projects, and those or others for customer work.  These should be configured to build and test every pull request.
```

2018-10-19 17:27 UTC, bengm requested changes
Looks good. Made one small suggested change.

2018-10-23 19:38 UTC, JeffreyMFarley commented
@bengm Is this OK now?

2018-10-24 00:47 UTC, bengm approved these changes

2018-10-24 00:47 UTC, merged